name: h-codex

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: h-codex-postgres
    env_file:
      - ../packages/core/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: h-codex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d h-codex']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
